#include "../src/maze.h"
#include "../src/qfeatures.h"
#include "../src/qghost.h"

#include <stdio.h>

#ifndef QSIM_WIDTH
#define QSIM_WIDTH 45
#endif
#ifndef QSIM_HEIGHT
#define QSIM_HEIGHT 21
#endif
#ifndef QSIM_STRIDE
#define QSIM_STRIDE 46
#endif
#ifndef QSIM_EPISODES
#define QSIM_EPISODES 4000
#endif
#ifndef QSIM_STEPS
#define QSIM_STEPS 400
#endif
#ifndef QSIM_MAZE_SEED_BASE
#define QSIM_MAZE_SEED_BASE 0x13579bdfu
#endif
#ifndef QSIM_MAZE_SEED_STEP
#define QSIM_MAZE_SEED_STEP 0x9e3779b9u
#endif
#ifndef QSIM_GHOST_SEED
#define QSIM_GHOST_SEED 0x2468ace1u
#endif
#ifndef QSIM_PLAYER_SEED
#define QSIM_PLAYER_SEED 0x10203040u
#endif
#define QSIM_WINDOW (QSIM_EPISODES / 10)

typedef struct QSimRng {
    unsigned int state;
} QSimRng;

typedef struct QSimStats {
    int total_steps;
    int catches;
} QSimStats;

static unsigned int qsim_next(QSimRng *rng)
{
    unsigned int x = rng->state;

    if (x == 0u) {
        x = 0x6d2b79f5u;
    }
    x ^= x << 13;
    x ^= x >> 17;
    x ^= x << 5;
    rng->state = x;
    return x;
}

static float qsim_random_unit(QSimRng *rng)
{
    return (float)(qsim_next(rng) >> 8) * (1.0f / 16777216.0f);
}

static int qsim_pick_valid(QSimRng *rng, const unsigned char valid[QFEAT_ACTIONS])
{
    int action;
    int count = 0;
    int pick;

    for (action = 0; action < QFEAT_ACTIONS; ++action) {
        if (valid[action] != 0u) {
            ++count;
        }
    }
    if (count == 0) {
        return -1;
    }

    pick = (int)(qsim_next(rng) % (unsigned int)count);
    for (action = 0; action < QFEAT_ACTIONS; ++action) {
        if (valid[action] != 0u) {
            if (pick == 0) {
                return action;
            }
            --pick;
        }
    }

    return -1;
}

static void qsim_move(int action, int *x, int *y)
{
    int dx;
    int dy;

    qfeat_action_delta(action, &dx, &dy);
    *x = qfeat_wrap_x(*x + dx, QSIM_WIDTH);
    *y += dy;
}

static int qsim_generate_maze(char map[QSIM_HEIGHT * QSIM_STRIDE],
                              MazeSpawns *spawns, int episode)
{
    unsigned int seed = QSIM_MAZE_SEED_BASE +
                        (unsigned int)episode * QSIM_MAZE_SEED_STEP;
    int attempt;

    for (attempt = 0; attempt < 64; ++attempt) {
        if (maze_generate(map, QSIM_STRIDE, QSIM_WIDTH, QSIM_HEIGHT,
                          seed + (unsigned int)attempt, episode % 3, 1,
                          spawns)) {
            return 1;
        }
    }

    return 0;
}

static void qsim_add_stat(QSimStats *stats, int steps, int caught)
{
    stats->total_steps += steps;
    if (caught) {
        ++stats->catches;
    }
}

static int qsim_write_table(const char *path, const QGhost *ghost)
{
    FILE *file = fopen(path, "w");
    int state;

    if (file == NULL) {
        return 0;
    }

    fprintf(file, "/* Auto-generated by tools/qsim.c -- do not edit. */\n");
    fprintf(file, "#ifndef TERMINAL_PACMAN_QTABLE_DATA_H\n");
    fprintf(file, "#define TERMINAL_PACMAN_QTABLE_DATA_H\n");
    fprintf(file, "static const float QTABLE_PRETRAINED[256][4] = {\n");
    for (state = 0; state < QGHOST_STATES; ++state) {
        fprintf(file, "    { %.6ff, %.6ff, %.6ff, %.6ff }%s\n",
                ghost->q[state][0], ghost->q[state][1],
                ghost->q[state][2], ghost->q[state][3],
                state == QGHOST_STATES - 1 ? "" : ",");
    }
    fprintf(file, "};\n");
    fprintf(file, "#endif\n");

    return fclose(file) == 0;
}

int main(void)
{
    QGhost ghost;
    QSimRng rng;
    QSimStats first;
    QSimStats last;
    int episode;

    qghost_init(&ghost, QSIM_GHOST_SEED);
    rng.state = QSIM_PLAYER_SEED;
    first.total_steps = 0;
    first.catches = 0;
    last.total_steps = 0;
    last.catches = 0;

    for (episode = 0; episode < QSIM_EPISODES; ++episode) {
        char map[QSIM_HEIGHT * QSIM_STRIDE];
        MazeSpawns spawns;
        int player_x;
        int player_y;
        int player_dir;
        int ghost_x;
        int ghost_y;
        int caught;
        int steps;

        if (!qsim_generate_maze(map, &spawns, episode)) {
            fprintf(stderr, "failed to generate maze for episode %d\n", episode);
            return 1;
        }
        if (spawns.ghost_count < 1) {
            fprintf(stderr, "maze has no learner ghost spawn for episode %d\n",
                    episode);
            return 1;
        }

        player_x = spawns.player_x;
        player_y = spawns.player_y;
        player_dir = 0;
        ghost_x = spawns.ghost_x[0];
        ghost_y = spawns.ghost_y[0];
        caught = 0;

        for (steps = 1; steps <= QSIM_STEPS; ++steps) {
            unsigned char player_valid[QFEAT_ACTIONS];
            unsigned char ghost_valid[QGHOST_ACTIONS];
            unsigned char next_valid[QGHOST_ACTIONS];
            int player_action;
            int state;
            int action;
            int old_ghost_x;
            int old_ghost_y;
            int next_state;
            float reward;

            qfeat_valid(map, QSIM_STRIDE, QSIM_WIDTH, QSIM_HEIGHT,
                        player_x, player_y, player_valid);
            player_action = -1;
            if (player_dir >= 1 && player_dir <= 4 &&
                player_valid[player_dir - 1] != 0u &&
                qsim_random_unit(&rng) < 0.75f) {
                player_action = player_dir - 1;
            }
            if (player_action < 0) {
                player_action = qsim_pick_valid(&rng, player_valid);
            }
            if (player_action >= 0) {
                qsim_move(player_action, &player_x, &player_y);
                player_dir = player_action + 1;
            } else {
                player_dir = 0;
            }

            state = qfeat_state(ghost_x, ghost_y, player_x, player_y,
                                player_dir);
            qfeat_valid(map, QSIM_STRIDE, QSIM_WIDTH, QSIM_HEIGHT,
                        ghost_x, ghost_y, ghost_valid);
            action = qghost_select(&ghost, state, ghost_valid);
            old_ghost_x = ghost_x;
            old_ghost_y = ghost_y;
            if (action >= 0 && ghost_valid[action] != 0u) {
                qsim_move(action, &ghost_x, &ghost_y);
            }

            reward = qfeat_reward(old_ghost_x, old_ghost_y,
                                  ghost_x, ghost_y, player_x, player_y);
            next_state = qfeat_state(ghost_x, ghost_y, player_x, player_y,
                                     player_dir);
            qfeat_valid(map, QSIM_STRIDE, QSIM_WIDTH, QSIM_HEIGHT,
                        ghost_x, ghost_y, next_valid);
            qghost_update(&ghost, state, action, reward, next_state,
                          next_valid);

            if (ghost_x == player_x && ghost_y == player_y) {
                caught = 1;
                break;
            }
        }
        if (!caught) {
            steps = QSIM_STEPS;
        }

        if (episode < QSIM_WINDOW) {
            qsim_add_stat(&first, steps, caught);
        }
        if (episode >= QSIM_EPISODES - QSIM_WINDOW) {
            qsim_add_stat(&last, steps, caught);
        }
    }

    if (!qsim_write_table("src/qtable_data.h", &ghost)) {
        fprintf(stderr, "failed to write src/qtable_data.h\n");
        return 1;
    }

    printf("first %d episodes: mean_steps=%.2f catch_rate=%.2f%%\n",
           QSIM_WINDOW, (double)first.total_steps / (double)QSIM_WINDOW,
           100.0 * (double)first.catches / (double)QSIM_WINDOW);
    printf("last %d episodes: mean_steps=%.2f catch_rate=%.2f%%\n",
           QSIM_WINDOW, (double)last.total_steps / (double)QSIM_WINDOW,
           100.0 * (double)last.catches / (double)QSIM_WINDOW);
    printf("summary: mean_steps %.2f -> %.2f, catch_rate %.2f%% -> %.2f%%\n",
           (double)first.total_steps / (double)QSIM_WINDOW,
           (double)last.total_steps / (double)QSIM_WINDOW,
           100.0 * (double)first.catches / (double)QSIM_WINDOW,
           100.0 * (double)last.catches / (double)QSIM_WINDOW);
    printf("wrote src/qtable_data.h\n");

    return 0;
}
