name: CI

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up MinGW
        if: runner.os == 'Windows'
        uses: egor-tensin/setup-mingw@v2

      - name: Build
        if: runner.os != 'Windows'
        run: make

      - name: Test
        if: runner.os != 'Windows'
        run: make test

      - name: Build
        if: runner.os == 'Windows'
        shell: powershell
        run: powershell -File build.ps1

      - name: Test
        if: runner.os == 'Windows'
        shell: powershell
        run: powershell -File build_tests.ps1
